"""
Complete Tarot Deck - 78 cards (Rider-Waite tradition)
Each card: id, name (EN), name_cn, number, arcana, element,
           keywords_upright, keywords_reversed, meaning_upright, meaning_reversed
"""
from dataclasses import dataclass, field


@dataclass
class TarotCard:
    id: int
    name: str
    name_cn: str
    number: str
    arcana: str           # "major" | "wands" | "cups" | "swords" | "pentacles"
    element: str          # "fire" | "water" | "air" | "earth" | "" (major)
    keywords_upright: list[str] = field(default_factory=list)
    keywords_reversed: list[str] = field(default_factory=list)
    meaning_upright: str = ""
    meaning_reversed: str = ""


# ═══════════════════════════════════════════════════════════════
#  Major Arcana (0-21)
# ═══════════════════════════════════════════════════════════════

MAJOR_ARCANA = [
    TarotCard(
        id=0, name="The Fool", name_cn="愚者", number="0",
        arcana="major", element="",
        keywords_upright=["新的开始", "冒险", "自由", "天真", "潜力"],
        keywords_reversed=["鲁莽", "犹豫", "冒险失败", "停滞"],
        meaning_upright="新的旅程即将开始，带着天真与勇气踏上未知之路。",
        meaning_reversed="冲动行事或过度犹豫，错失良机。",
    ),
    TarotCard(
        id=1, name="The Magician", name_cn="魔术师", number="I",
        arcana="major", element="",
        keywords_upright=["创造力", "意志力", "技巧", "资源充足", "显化"],
        keywords_reversed=["欺骗", "操纵", "能力不足", "浪费天赋"],
        meaning_upright="你拥有将想法变为现实的一切资源，行动吧。",
        meaning_reversed="天赋被误用，或方向不明确。",
    ),
    TarotCard(
        id=2, name="The High Priestess", name_cn="女祭司", number="II",
        arcana="major", element="",
        keywords_upright=["直觉", "神秘", "潜意识", "内在智慧", "等待"],
        keywords_reversed=["忽视直觉", "表面化", "秘密暴露", "困惑"],
        meaning_upright="倾听内心的声音，答案在沉默中浮现。",
        meaning_reversed="过于依赖理性，忽略了内心深处的指引。",
    ),
    TarotCard(
        id=3, name="The Empress", name_cn="皇后", number="III",
        arcana="major", element="",
        keywords_upright=["丰盛", "母性", "自然", "创造", "感性"],
        keywords_reversed=["依赖", "创造力枯竭", "过度放纵", "空虚"],
        meaning_upright="丰收与滋养的时刻，拥抱生命中的美好。",
        meaning_reversed="缺乏自我关怀或过度付出。",
    ),
    TarotCard(
        id=4, name="The Emperor", name_cn="皇帝", number="IV",
        arcana="major", element="",
        keywords_upright=["权威", "结构", "稳定", "领导力", "秩序"],
        keywords_reversed=["专制", "僵化", "控制欲", "缺乏纪律"],
        meaning_upright="建立秩序与规则，以理性引领方向。",
        meaning_reversed="过于刚硬或失去掌控力。",
    ),
    TarotCard(
        id=5, name="The Hierophant", name_cn="教皇", number="V",
        arcana="major", element="",
        keywords_upright=["传统", "信仰", "教导", "精神引导", "团体"],
        keywords_reversed=["打破常规", "非传统", "叛逆", "教条主义"],
        meaning_upright="遵循传统智慧，在信仰中找到力量。",
        meaning_reversed="质疑权威，走自己的路。",
    ),
    TarotCard(
        id=6, name="The Lovers", name_cn="恋人", number="VI",
        arcana="major", element="",
        keywords_upright=["爱情", "选择", "和谐", "价值观", "结合"],
        keywords_reversed=["不和谐", "价值观冲突", "错误选择", "分离"],
        meaning_upright="面临重要的选择，跟随内心做出决定。",
        meaning_reversed="关系中的失衡或选择困难。",
    ),
    TarotCard(
        id=7, name="The Chariot", name_cn="战车", number="VII",
        arcana="major", element="",
        keywords_upright=["胜利", "意志力", "决心", "克服障碍", "前进"],
        keywords_reversed=["失控", "方向混乱", "挫败", "缺乏自律"],
        meaning_upright="凭借坚定意志驾驭矛盾，驶向胜利。",
        meaning_reversed="失去方向或内在冲突未解决。",
    ),
    TarotCard(
        id=8, name="Strength", name_cn="力量", number="VIII",
        arcana="major", element="",
        keywords_upright=["内在力量", "勇气", "耐心", "慈悲", "柔韧"],
        keywords_reversed=["自我怀疑", "软弱", "缺乏自信", "冲动"],
        meaning_upright="以温柔的力量驯服内心的猛兽。",
        meaning_reversed="对自身力量的怀疑或压抑。",
    ),
    TarotCard(
        id=9, name="The Hermit", name_cn="隐者", number="IX",
        arcana="major", element="",
        keywords_upright=["内省", "独处", "智慧", "指引", "沉思"],
        keywords_reversed=["孤立", "逃避", "封闭", "迷失方向"],
        meaning_upright="退入内心深处，在孤独中找到答案。",
        meaning_reversed="过度封闭或害怕独处。",
    ),
    TarotCard(
        id=10, name="Wheel of Fortune", name_cn="命运之轮", number="X",
        arcana="major", element="",
        keywords_upright=["转折", "命运", "循环", "机遇", "变化"],
        keywords_reversed=["厄运", "抗拒变化", "失控", "停滞"],
        meaning_upright="命运的轮子在转动，接受变化带来的机遇。",
        meaning_reversed="抗拒必要的改变或遭遇逆境。",
    ),
    TarotCard(
        id=11, name="Justice", name_cn="正义", number="XI",
        arcana="major", element="",
        keywords_upright=["公正", "真相", "因果", "平衡", "法律"],
        keywords_reversed=["不公", "逃避责任", "偏见", "谎言"],
        meaning_upright="真相终将浮出水面，因果律正在运作。",
        meaning_reversed="不公正的对待或逃避应有的责任。",
    ),
    TarotCard(
        id=12, name="The Hanged Man", name_cn="倒吊人", number="XII",
        arcana="major", element="",
        keywords_upright=["牺牲", "放手", "新视角", "等待", "臣服"],
        keywords_reversed=["无谓牺牲", "拖延", "拒绝放手", "固执"],
        meaning_upright="换个角度看世界，暂停是为了更深的领悟。",
        meaning_reversed="无意义的拖延或不愿放手。",
    ),
    TarotCard(
        id=13, name="Death", name_cn="死神", number="XIII",
        arcana="major", element="",
        keywords_upright=["结束", "转变", "重生", "放下", "蜕变"],
        keywords_reversed=["抗拒改变", "停滞", "恐惧", "无法放手"],
        meaning_upright="旧的结束是新的开始，拥抱深刻的转变。",
        meaning_reversed="害怕结束而紧抓不放。",
    ),
    TarotCard(
        id=14, name="Temperance", name_cn="节制", number="XIV",
        arcana="major", element="",
        keywords_upright=["平衡", "耐心", "调和", "中庸", "治愈"],
        keywords_reversed=["失衡", "过度", "冲突", "缺乏耐心"],
        meaning_upright="在对立中找到平衡，以耐心调和一切。",
        meaning_reversed="走极端或缺乏节制。",
    ),
    TarotCard(
        id=15, name="The Devil", name_cn="恶魔", number="XV",
        arcana="major", element="",
        keywords_upright=["束缚", "欲望", "执念", "阴影", "物质主义"],
        keywords_reversed=["解脱", "觉醒", "打破束缚", "自由"],
        meaning_upright="正视内心的阴影，才能真正获得自由。",
        meaning_reversed="从束缚中解脱，重获自由。",
    ),
    TarotCard(
        id=16, name="The Tower", name_cn="塔", number="XVI",
        arcana="major", element="",
        keywords_upright=["突变", "崩塌", "觉醒", "破坏", "真相"],
        keywords_reversed=["恐惧改变", "灾难避免", "内部变革", "逃避"],
        meaning_upright="虚假的结构被摧毁，真相在废墟中显现。",
        meaning_reversed="避免了灾难但根基仍不稳。",
    ),
    TarotCard(
        id=17, name="The Star", name_cn="星星", number="XVII",
        arcana="major", element="",
        keywords_upright=["希望", "灵感", "宁静", "信念", "疗愈"],
        keywords_reversed=["失望", "失去信心", "绝望", "迷茫"],
        meaning_upright="在黑暗之后，星光指引你前行的方向。",
        meaning_reversed="对未来的希望变得渺茫。",
    ),
    TarotCard(
        id=18, name="The Moon", name_cn="月亮", number="XVIII",
        arcana="major", element="",
        keywords_upright=["幻觉", "潜意识", "恐惧", "梦境", "直觉"],
        keywords_reversed=["释放恐惧", "真相大白", "清醒", "理性"],
        meaning_upright="在月光下穿越幻象的迷雾，信任你的直觉。",
        meaning_reversed="从困惑中走出，看清真相。",
    ),
    TarotCard(
        id=19, name="The Sun", name_cn="太阳", number="XIX",
        arcana="major", element="",
        keywords_upright=["快乐", "成功", "活力", "光明", "温暖"],
        keywords_reversed=["短暂的快乐", "过度乐观", "自我中心"],
        meaning_upright="阳光普照，一切都在向好的方向发展。",
        meaning_reversed="快乐中有隐忧或过于自负。",
    ),
    TarotCard(
        id=20, name="Judgement", name_cn="审判", number="XX",
        arcana="major", element="",
        keywords_upright=["觉醒", "重生", "召唤", "反思", "宽恕"],
        keywords_reversed=["自我怀疑", "拒绝成长", "逃避审视"],
        meaning_upright="听从内心的召唤，做出重要的觉醒与决定。",
        meaning_reversed="拒绝面对过去或害怕改变。",
    ),
    TarotCard(
        id=21, name="The World", name_cn="世界", number="XXI",
        arcana="major", element="",
        keywords_upright=["完成", "成就", "圆满", "整合", "旅程终点"],
        keywords_reversed=["未完成", "停滞", "缺乏收尾", "空虚"],
        meaning_upright="一个完整的循环即将结束，你已收获成长。",
        meaning_reversed="功亏一篑或无法圆满收场。",
    ),
]


# ═══════════════════════════════════════════════════════════════
#  Minor Arcana - Wands (权杖/火)
# ═══════════════════════════════════════════════════════════════

WANDS = [
    TarotCard(id=22, name="Ace of Wands", name_cn="权杖王牌", number="Ace",
              arcana="wands", element="fire",
              keywords_upright=["灵感", "行动", "创造", "潜力"],
              keywords_reversed=["延迟", "缺乏方向", "失去热情"],
              meaning_upright="新的灵感如火焰般点燃，充满创造的能量。",
              meaning_reversed="热情消退或缺乏行动力。"),
    TarotCard(id=23, name="Two of Wands", name_cn="权杖二", number="2",
              arcana="wands", element="fire",
              keywords_upright=["计划", "决策", "远见", "探索"],
              keywords_reversed=["恐惧变化", "目光短浅", "安于现状"],
              meaning_upright="站在世界之巅，规划下一步的旅程。",
              meaning_reversed="害怕踏出舒适圈。"),
    TarotCard(id=24, name="Three of Wands", name_cn="权杖三", number="3",
              arcana="wands", element="fire",
              keywords_upright=["展望", "扩展", "领导力", "合作"],
              keywords_reversed=["障碍", "挫折", "缺乏远见"],
              meaning_upright="你的计划正在展开，机遇在远方等待。",
              meaning_reversed="计划受阻或目光不够长远。"),
    TarotCard(id=25, name="Four of Wands", name_cn="权杖四", number="4",
              arcana="wands", element="fire",
              keywords_upright=["庆祝", "和谐", "家园", "成就"],
              keywords_reversed=["不安定", "冲突", "缺乏归属感"],
              meaning_upright="值得庆祝的时刻，享受和谐与归属。",
              meaning_reversed="家庭或社区中的不和谐。"),
    TarotCard(id=26, name="Five of Wands", name_cn="权杖五", number="5",
              arcana="wands", element="fire",
              keywords_upright=["竞争", "冲突", "挑战", "成长"],
              keywords_reversed=["避免冲突", "内耗", "妥协"],
              meaning_upright="竞争带来成长，在冲突中磨练自己。",
              meaning_reversed="无谓的内斗或逃避必要竞争。"),
    TarotCard(id=27, name="Six of Wands", name_cn="权杖六", number="6",
              arcana="wands", element="fire",
              keywords_upright=["胜利", "认可", "自信", "荣耀"],
              keywords_reversed=["失败", "缺乏认可", "傲慢"],
              meaning_upright="凯旋归来，你赢得了应有的荣耀。",
              meaning_reversed="未被认可或过于自负。"),
    TarotCard(id=28, name="Seven of Wands", name_cn="权杖七", number="7",
              arcana="wands", element="fire",
              keywords_upright=["捍卫", "坚持", "勇气", "立场"],
              keywords_reversed=["退缩", "妥协", "缺乏勇气"],
              meaning_upright="坚守你的立场，勇气会为你赢得尊重。",
              meaning_reversed="在压力下放弃或退缩。"),
    TarotCard(id=29, name="Eight of Wands", name_cn="权杖八", number="8",
              arcana="wands", element="fire",
              keywords_upright=["速度", "行动", "消息", "进展"],
              keywords_reversed=["延迟", "挫折", "停滞"],
              meaning_upright="事情进展迅速，把握时机向前冲。",
              meaning_reversed="进展受阻或消息延迟。"),
    TarotCard(id=30, name="Nine of Wands", name_cn="权杖九", number="9",
              arcana="wands", element="fire",
              keywords_upright=["坚韧", "毅力", "防御", "最后考验"],
              keywords_reversed=["筋疲力尽", "放弃", "防御过度"],
              meaning_upright="你已经走了很远，再坚持一下就到终点。",
              meaning_reversed="身心疲惫，需要休息。"),
    TarotCard(id=31, name="Ten of Wands", name_cn="权杖十", number="10",
              arcana="wands", element="fire",
              keywords_upright=["负担", "责任", "压力", "过度劳累"],
              keywords_reversed=["卸下重担", "委托", "放松"],
              meaning_upright="承担了太多责任，学会适当放下。",
              meaning_reversed="学会放手或委托他人。"),
    TarotCard(id=32, name="Page of Wands", name_cn="权杖侍从", number="Page",
              arcana="wands", element="fire",
              keywords_upright=["探索", "热情", "新消息", "冒险精神"],
              keywords_reversed=["冲动", "缺乏方向", "失望"],
              meaning_upright="带着好奇心和热情去探索新的可能。",
              meaning_reversed="三分钟热度或方向不明。"),
    TarotCard(id=33, name="Knight of Wands", name_cn="权杖骑士", number="Knight",
              arcana="wands", element="fire",
              keywords_upright=["行动", "勇气", "冒险", "激情"],
              keywords_reversed=["鲁莽", "急躁", "缺乏耐心"],
              meaning_upright="以激情和勇气驱动，大胆向前。",
              meaning_reversed="冲动行事或半途而废。"),
    TarotCard(id=34, name="Queen of Wands", name_cn="权杖女王", number="Queen",
              arcana="wands", element="fire",
              keywords_upright=["自信", "独立", "温暖", "领导力"],
              keywords_reversed=["嫉妒", "自私", "控制欲"],
              meaning_upright="自信而温暖的领导者，散发独特魅力。",
              meaning_reversed="缺乏自信或过于强势。"),
    TarotCard(id=35, name="King of Wands", name_cn="权杖国王", number="King",
              arcana="wands", element="fire",
              keywords_upright=["领导", "远见", "魄力", "企业家精神"],
              keywords_reversed=["专横", "冲动", "缺乏远见"],
              meaning_upright="以魄力和远见领导，开创属于你的事业。",
              meaning_reversed="独断专行或缺乏耐心。"),
]


# ═══════════════════════════════════════════════════════════════
#  Minor Arcana - Cups (圣杯/水)
# ═══════════════════════════════════════════════════════════════

CUPS = [
    TarotCard(id=36, name="Ace of Cups", name_cn="圣杯王牌", number="Ace",
              arcana="cups", element="water",
              keywords_upright=["新感情", "直觉", "创造力", "丰盛"],
              keywords_reversed=["情感封闭", "空虚", "拒绝爱"],
              meaning_upright="情感的源泉涌出，新的爱与喜悦降临。",
              meaning_reversed="情感上的封闭或拒绝接受爱。"),
    TarotCard(id=37, name="Two of Cups", name_cn="圣杯二", number="2",
              arcana="cups", element="water",
              keywords_upright=["合作", "吸引力", "和谐", "伙伴关系"],
              keywords_reversed=["失衡", "分离", "沟通不畅"],
              meaning_upright="两颗心的联结，和谐的伙伴关系。",
              meaning_reversed="关系中的失衡或疏远。"),
    TarotCard(id=38, name="Three of Cups", name_cn="圣杯三", number="3",
              arcana="cups", element="water",
              keywords_upright=["庆祝", "友谊", "社交", "快乐"],
              keywords_reversed=["过度放纵", "社交疲劳", "孤立"],
              meaning_upright="与朋友一起庆祝，分享快乐时光。",
              meaning_reversed="社交过度或失去真正的友谊。"),
    TarotCard(id=39, name="Four of Cups", name_cn="圣杯四", number="4",
              arcana="cups", element="water",
              keywords_upright=["冥想", "不满", "沉思", "机会被忽视"],
              keywords_reversed=["觉醒", "接受", "重新投入"],
              meaning_upright="对现状不满，需要重新审视内心。",
              meaning_reversed="从冥想中醒来，发现新的机会。"),
    TarotCard(id=40, name="Five of Cups", name_cn="圣杯五", number="5",
              arcana="cups", element="water",
              keywords_upright=["失望", "悲伤", "失去", "沉溺过去"],
              keywords_reversed=["接受", "放下", "向前看"],
              meaning_upright="为失去的东西悲伤，但还有未被注意的希望。",
              meaning_reversed="接受过去，重新振作。"),
    TarotCard(id=41, name="Six of Cups", name_cn="圣杯六", number="6",
              arcana="cups", element="water",
              keywords_upright=["回忆", "童年", "纯真", "怀旧"],
              keywords_reversed=["活在过去", "不切实际", "成长"],
              meaning_upright="美好的回忆温暖你的心，纯真的快乐。",
              meaning_reversed="沉溺于过去或不切实际的幻想。"),
    TarotCard(id=42, name="Seven of Cups", name_cn="圣杯七", number="7",
              arcana="cups", element="water",
              keywords_upright=["幻想", "选择", "白日梦", "诱惑"],
              keywords_reversed=["清醒", "务实", "做出选择"],
              meaning_upright="面对众多选择和幻想，需要辨别真假。",
              meaning_reversed="从幻想中清醒，做出务实的选择。"),
    TarotCard(id=43, name="Eight of Cups", name_cn="圣杯八", number="8",
              arcana="cups", element="water",
              keywords_upright=["离开", "追寻", "放下", "精神探索"],
              keywords_reversed=["害怕离开", "逃避", "犹豫不决"],
              meaning_upright="放下已有的一切，踏上寻找更深意义的旅程。",
              meaning_reversed="害怕踏出改变的一步。"),
    TarotCard(id=44, name="Nine of Cups", name_cn="圣杯九", number="9",
              arcana="cups", element="water",
              keywords_upright=["满足", "愿望成真", "幸福", "富足"],
              keywords_reversed=["不满足", "贪婪", "表面幸福"],
              meaning_upright="你的愿望即将实现，内心充满满足。",
              meaning_reversed="物质满足但内心空虚。"),
    TarotCard(id=45, name="Ten of Cups", name_cn="圣杯十", number="10",
              arcana="cups", element="water",
              keywords_upright=["家庭幸福", "和谐", "情感圆满", "爱"],
              keywords_reversed=["家庭矛盾", "不和谐", "理想破灭"],
              meaning_upright="家庭幸福美满，情感生活圆满和谐。",
              meaning_reversed="家庭关系紧张或理想与现实的落差。"),
    TarotCard(id=46, name="Page of Cups", name_cn="圣杯侍从", number="Page",
              arcana="cups", element="water",
              keywords_upright=["创意", "直觉", "浪漫", "新消息"],
              keywords_reversed=["不成熟", "情绪化", "失望"],
              meaning_upright="创意的灵感从心底涌出，保持浪漫的心。",
              meaning_reversed="情绪不稳定或过于幼稚。"),
    TarotCard(id=47, name="Knight of Cups", name_cn="圣杯骑士", number="Knight",
              arcana="cups", element="water",
              keywords_upright=["浪漫", "魅力", "理想主义", "追求"],
              keywords_reversed=["不切实际", "情绪化", "失望"],
              meaning_upright="以浪漫的姿态追求心中的理想。",
              meaning_reversed="过于理想化或缺乏实际行动。"),
    TarotCard(id=48, name="Queen of Cups", name_cn="圣杯女王", number="Queen",
              arcana="cups", element="water",
              keywords_upright=["同理心", "直觉", "温柔", "情感智慧"],
              keywords_reversed=["情绪化", "依赖", "自我牺牲"],
              meaning_upright="以温柔和直觉的力量治愈他人。",
              meaning_reversed="情绪失控或过度依赖他人。"),
    TarotCard(id=49, name="King of Cups", name_cn="圣杯国王", number="King",
              arcana="cups", element="water",
              keywords_upright=["情感成熟", "平衡", "智慧", "外交"],
              keywords_reversed=["情绪压抑", "操控", "冷漠"],
              meaning_upright="在情感的海洋中游刃有余，成熟而智慧。",
              meaning_reversed="压抑情感或以情感操控他人。"),
]


# ═══════════════════════════════════════════════════════════════
#  Minor Arcana - Swords (宝剑/风)
# ═══════════════════════════════════════════════════════════════

SWORDS = [
    TarotCard(id=50, name="Ace of Swords", name_cn="宝剑王牌", number="Ace",
              arcana="swords", element="air",
              keywords_upright=["清晰", "真相", "突破", "正义"],
              keywords_reversed=["混乱", "误解", "暴力"],
              meaning_upright="思维清晰如剑，真相与正义的力量。",
              meaning_reversed="思绪混乱或误用智慧。"),
    TarotCard(id=51, name="Two of Swords", name_cn="宝剑二", number="2",
              arcana="swords", element="air",
              keywords_upright=["僵局", "选择困难", "回避", "平衡"],
              keywords_reversed=["打破僵局", "决定", "释放"],
              meaning_upright="蒙眼面对艰难的选择，内心在挣扎。",
              meaning_reversed="做出决定或打破僵局。"),
    TarotCard(id=52, name="Three of Swords", name_cn="宝剑三", number="3",
              arcana="swords", element="air",
              keywords_upright=["心碎", "背叛", "悲伤", "分离"],
              keywords_reversed=["释放悲伤", "原谅", "恢复"],
              meaning_upright="三把剑刺穿心脏，直面悲伤与背叛。",
              meaning_reversed="开始放下悲伤，走向疗愈。"),
    TarotCard(id=53, name="Four of Swords", name_cn="宝剑四", number="4",
              arcana="swords", element="air",
              keywords_upright=["休息", "恢复", "冥想", "暂停"],
              keywords_reversed=["焦躁不安", "过度劳累", "无法休息"],
              meaning_upright="在战斗之后需要充分的休息和恢复。",
              meaning_reversed="无法停下来休息或过度消耗。"),
    TarotCard(id=54, name="Five of Swords", name_cn="宝剑五", number="5",
              arcana="swords", element="air",
              keywords_upright=["冲突", "失败", "自私", "争斗"],
              keywords_reversed=["和解", "放下执念", "宽恕"],
              meaning_upright="赢得战斗却失去了什么，胜利的代价。",
              meaning_reversed="选择和解而非继续争斗。"),
    TarotCard(id=55, name="Six of Swords", name_cn="宝剑六", number="6",
              arcana="swords", element="air",
              keywords_upright=["过渡", "离开", "前进", "疗愈之旅"],
              keywords_reversed=["停滞", "无法前进", "困难重重"],
              meaning_upright="乘船离开风暴，驶向平静的彼岸。",
              meaning_reversed="无法离开困境或旅途艰难。"),
    TarotCard(id=56, name="Seven of Swords", name_cn="宝剑七", number="7",
              arcana="swords", element="air",
              keywords_upright=["策略", "机智", "独自行动", "秘密"],
              keywords_reversed=["暴露", "诚实", "面对后果"],
              meaning_upright="以智取胜，策略性地达成目标。",
              meaning_reversed="秘密被揭穿或需要坦诚面对。"),
    TarotCard(id=57, name="Eight of Swords", name_cn="宝剑八", number="8",
              arcana="swords", element="air",
              keywords_upright=["束缚", "无力感", "恐惧", "困境"],
              keywords_reversed=["释放", "自由", "看清真相"],
              meaning_upright="被恐惧和限制包围，但自由其实近在咫尺。",
              meaning_reversed="打破心理束缚，重获自由。"),
    TarotCard(id=58, name="Nine of Swords", name_cn="宝剑九", number="9",
              arcana="swords", element="air",
              keywords_upright=["焦虑", "噩梦", "痛苦", "失眠"],
              keywords_reversed=["释放恐惧", "希望", "好转"],
              meaning_upright="深夜的焦虑和恐惧，但很多只是想象。",
              meaning_reversed="最黑暗的时刻即将过去。"),
    TarotCard(id=59, name="Ten of Swords", name_cn="宝剑十", number="10",
              arcana="swords", element="air",
              keywords_upright=["结束", "背叛", "谷底", "终结"],
              keywords_reversed=["恢复", "重生", "触底反弹"],
              meaning_upright="到了最低谷，但也意味着不会再更差了。",
              meaning_reversed="从最坏的情况中恢复，新的开始。"),
    TarotCard(id=60, name="Page of Swords", name_cn="宝剑侍从", number="Page",
              arcana="swords", element="air",
              keywords_upright=["好奇心", "学习", "敏锐", "新想法"],
              keywords_reversed=["八卦", "冲动", "缺乏深度"],
              meaning_upright="以敏锐的头脑探索新的知识领域。",
              meaning_reversed="流于表面或传播不实信息。"),
    TarotCard(id=61, name="Knight of Swords", name_cn="宝剑骑士", number="Knight",
              arcana="swords", element="air",
              keywords_upright=["果断", "迅速", "追求真相", "行动力"],
              keywords_reversed=["鲁莽", "冲动", "缺乏耐心"],
              meaning_upright="如风般迅速果断，直奔目标。",
              meaning_reversed="过于急躁或缺乏策略。"),
    TarotCard(id=62, name="Queen of Swords", name_cn="宝剑女王", number="Queen",
              arcana="swords", element="air",
              keywords_upright=["独立", "清晰", "公正", "直觉"],
              keywords_reversed=["冷酷", "刻薄", "孤立"],
              meaning_upright="以清晰的头脑和公正的心做出判断。",
              meaning_reversed="过于冷酷或缺乏同情心。"),
    TarotCard(id=63, name="King of Swords", name_cn="宝剑国王", number="King",
              arcana="swords", element="air",
              keywords_upright=["权威", "公正", "智慧", "领导力"],
              keywords_reversed=["独裁", "冷酷", "滥用权力"],
              meaning_upright="以理性和公正领导，明断是非。",
              meaning_reversed="权力被滥用或过于冷酷无情。"),
]


# ═══════════════════════════════════════════════════════════════
#  Minor Arcana - Pentacles (星币/土)
# ═══════════════════════════════════════════════════════════════

PENTACLES = [
    TarotCard(id=64, name="Ace of Pentacles", name_cn="星币王牌", number="Ace",
              arcana="pentacles", element="earth",
              keywords_upright=["新机会", "财富", "稳定", "物质"],
              keywords_reversed=["错失机会", "不稳定", "物质匮乏"],
              meaning_upright="物质世界的新机会出现，把握住它。",
              meaning_reversed="财务上的失误或错过机会。"),
    TarotCard(id=65, name="Two of Pentacles", name_cn="星币二", number="2",
              arcana="pentacles", element="earth",
              keywords_upright=["平衡", "灵活性", "适应", "多任务"],
              keywords_reversed=["失衡", "压力过大", "混乱"],
              meaning_upright="在多个事务间灵活切换，保持平衡。",
              meaning_reversed="被太多事务压垮。"),
    TarotCard(id=66, name="Three of Pentacles", name_cn="星币三", number="3",
              arcana="pentacles", element="earth",
              keywords_upright=["团队合作", "技能", "质量", "协作"],
              keywords_reversed=["缺乏团队精神", "平庸", "不被认可"],
              meaning_upright="与他人协作，用专业技能创造价值。",
              meaning_reversed="团队不和或未被认可。"),
    TarotCard(id=67, name="Four of Pentacles", name_cn="星币四", number="4",
              arcana="pentacles", element="earth",
              keywords_upright=["保守", "安全", "控制", "储蓄"],
              keywords_reversed=["贪婪", "吝啬", "过度控制"],
              meaning_upright="守住你的财富，但也别忘了分享。",
              meaning_reversed="过于执着于物质或害怕失去。"),
    TarotCard(id=68, name="Five of Pentacles", name_cn="星币五", number="5",
              arcana="pentacles", element="earth",
              keywords_upright=["困难", "贫困", "孤独", "被忽视"],
              keywords_reversed=["恢复", "帮助", "好转"],
              meaning_upright="在困境中行走，但别忘了身边有援助。",
              meaning_reversed="从困难中走出，获得帮助。"),
    TarotCard(id=69, name="Six of Pentacles", name_cn="星币六", number="6",
              arcana="pentacles", element="earth",
              keywords_upright=["慷慨", "分享", "公平", "慈善"],
              keywords_reversed=["不公平", "利用", "自私"],
              meaning_upright="慷慨地分享你的资源，获得与给予的平衡。",
              meaning_reversed="不平等的关系或利用他人。"),
    TarotCard(id=70, name="Seven of Pentacles", name_cn="星币七", number="7",
              arcana="pentacles", element="earth",
              keywords_upright=["耐心", "等待", "评估", "长期投资"],
              keywords_reversed=["缺乏耐心", "短视", "失望"],
              meaning_upright="耐心等待收获的时刻，评估你的投资。",
              meaning_reversed="急于求成或方向错误。"),
    TarotCard(id=71, name="Eight of Pentacles", name_cn="星币八", number="8",
              arcana="pentacles", element="earth",
              keywords_upright=["专注", "精益求精", "勤奋", "技能"],
              keywords_reversed=["敷衍", "缺乏动力", "低质量"],
              meaning_upright="专注于打磨技能，精益求精。",
              meaning_reversed="敷衍了事或缺乏上进心。"),
    TarotCard(id=72, name="Nine of Pentacles", name_cn="星币九", number="9",
              arcana="pentacles", element="earth",
              keywords_upright=["独立", "富足", "优雅", "自律"],
              keywords_reversed=["依赖", "浪费", "不劳而获"],
              meaning_upright="通过自律获得物质和精神的双重富足。",
              meaning_reversed="过度依赖他人或挥霍无度。"),
    TarotCard(id=73, name="Ten of Pentacles", name_cn="星币十", number="10",
              arcana="pentacles", element="earth",
              keywords_upright=["财富", "传承", "家庭", "稳定"],
              keywords_reversed=["家庭矛盾", "遗产纠纷", "不稳定"],
              meaning_upright="丰厚的物质积累，建立持久的家族传承。",
              meaning_reversed="财务纠纷或家庭不稳定。"),
    TarotCard(id=74, name="Page of Pentacles", name_cn="星币侍从", number="Page",
              arcana="pentacles", element="earth",
              keywords_upright=["学习", "实用", "新机会", "专注"],
              keywords_reversed=["懒惰", "缺乏目标", "浪费时间"],
              meaning_upright="以务实的态度学习新技能，把握机会。",
              meaning_reversed="缺乏学习动力或目标不明确。"),
    TarotCard(id=75, name="Knight of Pentacles", name_cn="星币骑士", number="Knight",
              arcana="pentacles", element="earth",
              keywords_upright=["勤奋", "可靠", "耐心", "实际"],
              keywords_reversed=["固执", "懒惰", "缺乏变通"],
              meaning_upright="踏实可靠地一步步达成目标。",
              meaning_reversed="过于保守或缺乏行动力。"),
    TarotCard(id=76, name="Queen of Pentacles", name_cn="星币女王", number="Queen",
              arcana="pentacles", element="earth",
              keywords_upright=["务实", "温暖", "丰盛", "照顾"],
              keywords_reversed=["过度操劳", "物质主义", "忽视自我"],
              meaning_upright="以温暖和务实的方式创造丰盛的生活。",
              meaning_reversed="过度关注物质或忽略自身需求。"),
    TarotCard(id=77, name="King of Pentacles", name_cn="星币国王", number="King",
              arcana="pentacles", element="earth",
              keywords_upright=["成功", "财富", "领导力", "稳定"],
              keywords_reversed=["贪婪", "固执", "物质主义"],
              meaning_upright="在物质世界取得巨大成功，稳健而富有。",
              meaning_reversed="过于追求物质或固执己见。"),
]


# ═══════════════════════════════════════════════════════════════
#  Complete Deck
# ═══════════════════════════════════════════════════════════════

ALL_CARDS = MAJOR_ARCANA + WANDS + CUPS + SWORDS + PENTACLES
CARD_BY_ID = {card.id: card for card in ALL_CARDS}

# Element display info
ELEMENT_INFO = {
    "fire": {"symbol": "🜂", "name": "火", "color": (255, 100, 50)},
    "water": {"symbol": "🜄", "name": "水", "color": (78, 205, 196)},
    "air": {"symbol": "🜁", "name": "风", "color": (200, 200, 220)},
    "earth": {"symbol": "🜃", "name": "土", "color": (160, 140, 80)},
}
